rdf_dirs, rdf_files = glob_wildcards("../../../all_data/relation_extraction/data/gaivi_test/2020_02_23/rdf/{dir}/{id}.rdf")

rule all:
    input:
        "../../../all_data/relation_extraction/data/rdf_processing/logs/{dir}/{id}.log"

# rule all:
#     input:
#         "../examples/03RtwjsrPh.ranking"

rule edgelist:
    input:
        "../../../all_data/relation_extraction/data/gaivi_test/2020_02_23/rdf/{dir}/{id}.rdf"
    output:
        "../../../all_data/relation_extraction/data/rdf_processing/edgelists/{dir}/{id}.edgelist",
        "../../../all_data/relation_extraction/data/rdf_processing/nodemaps/{dir}/{id}.nodemap"
    script:
        "./edgelist.py"

rule vectorize_graph:
    input:
        "../../../all_data/relation_extraction/data/rdf_processing/edgelists/{dir}/{id}.edgelist"
    output:
        "../../../all_data/relation_extraction/data/rdf_processing/node_vectors/{dir}/{id}.emd"
    shell:
        "python node2vec/src/main.py --input {input} --output {output}"

rule distance_rank:
    input:
        "../../../all_data/relation_extraction/data/rdf_processing/node_vectors/{dir}/{id}.emd",
        "../../../all_data/relation_extraction/data/rdf_processing/nodemaps/{dir}/{id}.nodemap"
    output:
        "../../../all_data/relation_extraction/data/rdf_processing/rankings/{dir}/{id}.ranking"
    script:
        "./rank.py"

rule analyze_ranking:
    input:
        "../../../all_data/relation_extraction/data/entity_tagged/",
        "../../../all_data/relation_extraction/data/rdf_processing/rankings/{dir}/{id}.ranking",
        "../../../all_data/relation_extraction/data/gaivi_test/2020_02_23/rdf/{dir}/{id}.rdf"
    output:
    log:
        "../../../all_data/relation_extraction/data/rdf_processing/logs/{dir}/{id}.log"
    script:
        "./compare_nodes.py"